# Generated by Django 4.0.6 on 2022-07-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
