# Generated by Django 4.0.6 on 2022-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('openyear', models.IntegerField(default='', null=True, verbose_name='개봉 년도')),
                ('genre', models.CharField(choices=[('a', '액션'), ('b', '범죄'), ('c', 'SF'), ('d', '로맨스'), ('e', '코미디'), ('f', '공포')], max_length=1, null=True, verbose_name='장르')),
                ('star', models.IntegerField(verbose_name='별점')),
                ('runningtime', models.CharField(max_length=50, verbose_name='러닝타임')),
                ('moviereview', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actor', models.CharField(max_length=50, verbose_name='배우')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
